// Client-side fallback lamps (static data only)
export interface Lamp {
  key: string
  name: string
  image: string
  price: number
  description?: string
}

// Descriptions for each lamp based on their spiritual meaning
const LAMP_DESCRIPTIONS: Record<string, string> = {
  '平安灯': '祈求平安健康，守护身心安宁，远离灾祸困扰。',
  '健康灯': '祈愿身体康健，精力充沛，远离疾病困扰。',
  '财运灯': '招财进宝，财运亨通，事业蒸蒸日上，财富滚滚来。',
  '招财灯': '广开财源，财运滚滚，生意兴隆财富多。',
  '暴富灯': '祈求意外之财，横财来临，财富飙升。',
  '回财灯': '追回失去的财富，财源重现，失而复得。',
  '偏财灯': '激活偏财运势，赌运提升，横财机遇。',
  '姻缘灯': '祈求姻缘美满，爱情甜蜜，找到心仪的另一半。',
  '正缘桃花灯': '招正缘桃花，良缘善缘，真爱相遇。',
  '斩烂桃花灯': '斩断烂桃花，驱逐破坏，重获清净。',
  '事业灯': '助力事业有成，前程似锦，工作顺利步步高。',
  '文昌灯': '开启文昌运，学业进步，考试顺利金榜题名。',
  '学业灯': '祈求学业进步，金榜题名，智慧增长才华展。',
  '智慧灯': '开启智慧之门，头脑清晰，决策明智事业兴。',
  '求子灯': '祈求送子娘娘保佑，早得贵子，家庭圆满。',
  '安产灯': '祈求平安顺产，母子安康，生产顺利。',
  '添寿灯': '祈愿长命百岁，健康长寿，福寿双全。',
  '好运灯': '汇聚好运气运，诸事顺利，好事连连。',
  '消灾灯': '消除灾厄烦恼，趋吉避凶，化解危险。',
  '除秽灯': '净化身心，驱除邪气，清净光明。',
  '防小人灯': '防范小人陷害，事业无忧，前程光明。',
  '贵人灯': '贵人相助，人脉拓展，机遇眷顾。',
  '本命灯': '守护本命，增运加持，人生顺畅。',
  '太岁灯': '化解太岁冲克，平安度过本年，化凶为吉。',
  '三宝灯': '供奉三宝，修行护佑，身心清净。',
  '五福灯': '五福临门，福禄寿喜财，圆满人生。',
  '七星灯': '七星护驾，神力加持，大吉大利。',
  '九子离火灯': '九子齐心，火焰旺盛，事业辉煌。',
  '传愿灯': '传递愿力，心想事成，梦想成真。',
  '追忆灯': '缅怀故人，祭祀寄托，永远怀念。',
  '忏悔灯': '忏悔往昔，洗净罪孽，重获新生。',
  '顺风顺水灯': '一帆风顺，万事顺心，诸事如意。',
  '爱宠无忧灯': '祝福宠物安康，陪伴永远，爱宠无忧。',
  '发横财灯': '发横财，意外之喜，财运爆棚。',
}

export const FALLBACK_LAMPS: Lamp[] = [
  {
    key: 'lamp_1',
    name: '平安灯',
    image: '/images/平安灯.png',
    price: 19.9,
    description: LAMP_DESCRIPTIONS['平安灯'],
  },
  {
    key: 'lamp_2',
    name: '健康灯',
    image: '/images/健康灯.png',
    price: 19.9,
    description: LAMP_DESCRIPTIONS['健康灯'],
  },
  {
    key: 'lamp_3',
    name: '财运灯',
    image: '/images/财运灯.png',
    price: 19.9,
    description: LAMP_DESCRIPTIONS['财运灯'],
  },
  {
    key: 'lamp_4',
    name: '招财灯',
    image: '/images/招财灯.png',
    price: 19.9,
    description: LAMP_DESCRIPTIONS['招财灯'],
  },
  {
    key: 'lamp_5',
    name: '暴富灯',
    image: '/images/暴富灯.png',
    price: 19.9,
    description: LAMP_DESCRIPTIONS['暴富灯'],
  },
  {
    key: 'lamp_6',
    name: '回财灯',
    image: '/images/回财灯.png',
    price: 19.9,
    description: LAMP_DESCRIPTIONS['回财灯'],
  },
  {
    key: 'lamp_7',
    name: '偏财灯',
    image: '/images/偏财灯.png',
    price: 19.9,
    description: LAMP_DESCRIPTIONS['偏财灯'],
  },
  {
    key: 'lamp_8',
    name: '姻缘灯',
    image: '/images/姻缘灯.png',
    price: 19.9,
    description: LAMP_DESCRIPTIONS['姻缘灯'],
  },
  {
    key: 'lamp_9',
    name: '正缘桃花灯',
    image: '/images/正缘桃花灯.png',
    price: 19.9,
    description: LAMP_DESCRIPTIONS['正缘桃花灯'],
  },
  {
    key: 'lamp_10',
    name: '斩烂桃花灯',
    image: '/images/斩烂桃花灯.png',
    price: 19.9,
    description: LAMP_DESCRIPTIONS['斩烂桃花灯'],
  },
  {
    key: 'lamp_11',
    name: '事业灯',
    image: '/images/p4.jpg',
    price: 19.9,
    description: LAMP_DESCRIPTIONS['事业灯'],
  },
  {
    key: 'lamp_12',
    name: '文昌灯',
    image: '/images/文昌灯.png',
    price: 19.9,
    description: LAMP_DESCRIPTIONS['文昌灯'],
  },
  {
    key: 'lamp_13',
    name: '智慧灯',
    image: '/images/智慧灯.png',
    price: 19.9,
    description: LAMP_DESCRIPTIONS['智慧灯'],
  },
  {
    key: 'lamp_14',
    name: '求子灯',
    image: '/images/求子灯.png',
    price: 19.9,
    description: LAMP_DESCRIPTIONS['求子灯'],
  },
  {
    key: 'lamp_15',
    name: '安产灯',
    image: '/images/安产灯.png',
    price: 19.9,
    description: LAMP_DESCRIPTIONS['安产灯'],
  },
  {
    key: 'lamp_16',
    name: '添寿灯',
    image: '/images/添寿灯.png',
    price: 19.9,
    description: LAMP_DESCRIPTIONS['添寿灯'],
  },
  {
    key: 'lamp_17',
    name: '好运灯',
    image: '/images/好运灯.png',
    price: 19.9,
    description: LAMP_DESCRIPTIONS['好运灯'],
  },
  {
    key: 'lamp_18',
    name: '消灾灯',
    image: '/images/消灾灯.png',
    price: 19.9,
    description: LAMP_DESCRIPTIONS['消灾灯'],
  },
  {
    key: 'lamp_19',
    name: '除秽灯',
    image: '/images/除秽灯.png',
    price: 19.9,
    description: LAMP_DESCRIPTIONS['除秽灯'],
  },
  {
    key: 'lamp_20',
    name: '防小人灯',
    image: '/images/防小人灯.png',
    price: 19.9,
    description: LAMP_DESCRIPTIONS['防小人灯'],
  },
  {
    key: 'lamp_21',
    name: '贵人灯',
    image: '/images/贵人灯.png',
    price: 19.9,
    description: LAMP_DESCRIPTIONS['贵人灯'],
  },
  {
    key: 'lamp_22',
    name: '本命灯',
    image: '/images/本命灯.png',
    price: 19.9,
    description: LAMP_DESCRIPTIONS['本命灯'],
  },
  {
    key: 'lamp_23',
    name: '太岁灯',
    image: '/images/太岁灯.png',
    price: 19.9,
    description: LAMP_DESCRIPTIONS['太岁灯'],
  },
  {
    key: 'lamp_24',
    name: '三宝灯',
    image: '/images/三宝灯.png',
    price: 19.9,
    description: LAMP_DESCRIPTIONS['三宝灯'],
  },
  {
    key: 'lamp_25',
    name: '五福灯',
    image: '/images/五福灯.png',
    price: 19.9,
    description: LAMP_DESCRIPTIONS['五福灯'],
  },
  {
    key: 'lamp_26',
    name: '七星灯',
    image: '/images/七星灯.png',
    price: 19.9,
    description: LAMP_DESCRIPTIONS['七星灯'],
  },
  {
    key: 'lamp_27',
    name: '九子离火灯',
    image: '/images/九子离火灯.png',
    price: 19.9,
    description: LAMP_DESCRIPTIONS['九子离火灯'],
  },
  {
    key: 'lamp_28',
    name: '传愿灯',
    image: '/images/传愿灯.png',
    price: 19.9,
    description: LAMP_DESCRIPTIONS['传愿灯'],
  },
  {
    key: 'lamp_29',
    name: '追忆灯',
    image: '/images/追忆灯.png',
    price: 19.9,
    description: LAMP_DESCRIPTIONS['追忆灯'],
  },
  {
    key: 'lamp_30',
    name: '忏悔灯',
    image: '/images/忏悔灯.png',
    price: 19.9,
    description: LAMP_DESCRIPTIONS['忏悔灯'],
  },
  {
    key: 'lamp_31',
    name: '顺风顺水灯',
    image: '/images/顺风顺水灯.png',
    price: 19.9,
    description: LAMP_DESCRIPTIONS['顺风顺水灯'],
  },
  {
    key: 'lamp_32',
    name: '爱宠无忧灯',
    image: '/images/爱宠无忧灯.png',
    price: 19.9,
    description: LAMP_DESCRIPTIONS['爱宠无忧灯'],
  },
  {
    key: 'lamp_33',
    name: '发横财灯',
    image: '/images/发横财灯.png',
    price: 19.9,
    description: LAMP_DESCRIPTIONS['发横财灯'],
  },
  {
    key: 'lamp_34',
    name: '四季平安灯',
    image: '/images/四季平安灯.png',
    price: 19.9,
    description: '四季平安，四时顺遂，全年吉祥安康。',
  },
]
