-- Migration: Sync lamps table with available lamp images
-- Created: 2025-11-15
-- Description: Ensures that every prayer lamp image in public/images has a
--              corresponding database record with a real UUID generated by
--              PostgreSQL. Missing lamps are inserted while existing lamp
--              records are left untouched so that purchase history remains
--              intact.

-- Insert any missing lamps based on the current set of PNG images.
-- We only insert new rows; existing lamps keep their current status and
-- timestamps.
INSERT INTO lamps (lamp_key, status, created_at, updated_at)
VALUES
  ('七星灯', 'unlit', NOW(), NOW()),
  ('三宝灯', 'unlit', NOW(), NOW()),
  ('九子离火灯', 'unlit', NOW(), NOW()),
  ('五福灯', 'unlit', NOW(), NOW()),
  ('传愿灯', 'unlit', NOW(), NOW()),
  ('偏财灯', 'unlit', NOW(), NOW()),
  ('健康灯', 'unlit', NOW(), NOW()),
  ('发横财灯', 'unlit', NOW(), NOW()),
  ('四季平安灯', 'unlit', NOW(), NOW()),
  ('回财灯', 'unlit', NOW(), NOW()),
  ('太岁灯', 'unlit', NOW(), NOW()),
  ('好运灯', 'unlit', NOW(), NOW()),
  ('姻缘灯', 'unlit', NOW(), NOW()),
  ('安产灯', 'unlit', NOW(), NOW()),
  ('平安灯', 'unlit', NOW(), NOW()),
  ('忏悔灯', 'unlit', NOW(), NOW()),
  ('招财灯', 'unlit', NOW(), NOW()),
  ('文昌灯', 'unlit', NOW(), NOW()),
  ('斩烂桃花灯', 'unlit', NOW(), NOW()),
  ('智慧灯', 'unlit', NOW(), NOW()),
  ('暴富灯', 'unlit', NOW(), NOW()),
  ('本命灯', 'unlit', NOW(), NOW()),
  ('正缘桃花灯', 'unlit', NOW(), NOW()),
  ('求子灯', 'unlit', NOW(), NOW()),
  ('消灾灯', 'unlit', NOW(), NOW()),
  ('添寿灯', 'unlit', NOW(), NOW()),
  ('爱宠无忧灯', 'unlit', NOW(), NOW()),
  ('贵人灯', 'unlit', NOW(), NOW()),
  ('追忆灯', 'unlit', NOW(), NOW()),
  ('防小人灯', 'unlit', NOW(), NOW()),
  ('除秽灯', 'unlit', NOW(), NOW()),
  ('顺风顺水灯', 'unlit', NOW(), NOW())
ON CONFLICT (lamp_key) DO NOTHING;

-- Optional verification (run manually after migration):
-- SELECT id, lamp_key FROM lamps WHERE lamp_key IN (
--   '七星灯','三宝灯','九子离火灯','五福灯','传愿灯','偏财灯','健康灯','发横财灯',
--   '四季平安灯','回财灯','太岁灯','好运灯','姻缘灯','安产灯','平安灯','忏悔灯',
--   '招财灯','文昌灯','斩烂桃花灯','智慧灯','暴富灯','本命灯','正缘桃花灯','求子灯',
--   '消灾灯','添寿灯','爱宠无忧灯','贵人灯','追忆灯','防小人灯','除秽灯','顺风顺水灯'
-- ) ORDER BY lamp_key;
